server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ecom-db
    username: postgres
    password: aash@1234
  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.
    show-sql: true
